"use client";

import React, { useEffect, useRef } from "react";
import gsap from "gsap";
import FloatingCards from "./hero/floating-cards";

export default function HeroSection() {
  const sectionRef = useRef<HTMLElement>(null);
  const line1Ref = useRef<HTMLDivElement>(null);
  const line2Ref = useRef<HTMLDivElement>(null);
  const line3Ref = useRef<HTMLDivElement>(null);
  const accentRef = useRef<HTMLSpanElement>(null);
  const subRef = useRef<HTMLParagraphElement>(null);
  const ctaRef = useRef<HTMLDivElement>(null);
  const trustRef = useRef<HTMLDivElement>(null);
  const cardsRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const tl = gsap.timeline({ delay: 0.2 });

    tl.fromTo(
      cardsRef.current,
      { opacity: 0, scale: 1.05 },
      { opacity: 1, scale: 1, duration: 1.8, ease: "power2.out" },
      0
    );
    tl.fromTo(
      line1Ref.current,
      { x: -80, opacity: 0 },
      { x: 0, opacity: 1, duration: 1, ease: "power3.out" },
      0.3
    );
    tl.fromTo(
      line2Ref.current,
      { y: 60, opacity: 0 },
      { y: 0, opacity: 1, duration: 1, ease: "power3.out" },
      0.5
    );
    tl.fromTo(
      line3Ref.current,
      { x: 80, opacity: 0 },
      { x: 0, opacity: 1, duration: 1, ease: "power3.out" },
      0.7
    );
    tl.fromTo(
      accentRef.current,
      { scale: 0.9, opacity: 0 },
      { scale: 1, opacity: 1, duration: 1.2, ease: "power3.out" },
      0.9
    );
    tl.fromTo(
      [subRef.current, ctaRef.current, trustRef.current],
      { y: 30, opacity: 0 },
      { y: 0, opacity: 1, duration: 0.8, stagger: 0.12, ease: "power2.out" },
      1.2
    );

    return () => { tl.kill(); };
  }, []);

  return (
    <section
      ref={sectionRef}
      id="hero"
      className="relative min-h-[100dvh] flex items-end overflow-hidden pb-20 lg:pb-28"
    >
      {/* Floating cards background — VISIBLE */}
      <div ref={cardsRef} className="absolute inset-0 opacity-0 z-0">
        <FloatingCards />
      </div>

      {/* White gradient overlays for text readability */}
      <div className="absolute inset-0 bg-gradient-to-b from-white/95 via-white/60 to-white/95 z-[1] pointer-events-none" />
      <div className="absolute inset-0 bg-gradient-to-r from-white/80 via-transparent to-white/80 z-[1] pointer-events-none" />

      {/* Dot pattern texture */}
      <div className="absolute inset-0 dot-pattern opacity-50 z-[1] pointer-events-none" />

      {/* Content */}
      <div className="relative z-10 w-full max-w-[1400px] mx-auto px-6 lg:px-12">
        {/* Eyebrow */}
        <p className="text-violet text-[10px] font-sans font-medium tracking-[0.3em] uppercase mb-8 lg:mb-12">
          AI Creative Studio — Est. 2024
        </p>

        {/* Asymmetric headline */}
        <div className="relative">
          <div ref={line1Ref} className="overflow-hidden">
            <h1 className="font-serif text-[clamp(3rem,10vw,8rem)] leading-[0.92] tracking-[-0.02em] text-gray-900 uppercase">
              AI-powered
            </h1>
          </div>

          <div ref={line2Ref} className="overflow-hidden ml-[2vw] lg:ml-[6vw] -mt-1 lg:-mt-3">
            <h1 className="font-serif text-[clamp(3.5rem,12vw,10rem)] leading-[0.88] tracking-[-0.03em] text-gray-900/90">
              visuals
            </h1>
          </div>

          <div ref={line3Ref} className="overflow-hidden text-right lg:text-left lg:ml-[30vw] -mt-1 lg:-mt-4">
            <h1 className="font-serif text-[clamp(2.5rem,8vw,6.5rem)] leading-[0.92] tracking-[-0.02em] text-gray-900/60">
              that convert
            </h1>
          </div>

          {/* Accent word */}
          <div className="absolute right-0 lg:right-12 bottom-0 lg:bottom-auto lg:top-1/2 lg:-translate-y-1/3">
            <span
              ref={accentRef}
              className="font-serif text-[clamp(2.5rem,8vw,6.5rem)] leading-[0.88] italic text-violet block"
            >
              at scale.
            </span>
          </div>
        </div>

        {/* Bottom bar */}
        <div className="mt-12 lg:mt-20 flex flex-col lg:flex-row lg:items-end lg:justify-between gap-8">
          <p
            ref={subRef}
            className="font-sans text-sm lg:text-base text-gray-500 max-w-md leading-relaxed"
          >
            Product photography, UGC videos, ad creatives, and websites —
            generated by AI, refined by designers. Studio quality without the
            studio price.
          </p>

          <div ref={ctaRef} className="flex items-center gap-5">
            <a
              href="#contact"
              className="group relative px-7 py-3.5 bg-violet text-white text-[11px] font-sans font-medium tracking-[0.18em] uppercase overflow-hidden hover:bg-violet-light transition-colors duration-500"
            >
              Start Your Project
            </a>
            <a
              href="#work"
              className="font-sans text-[11px] text-gray-400 tracking-[0.18em] uppercase hover:text-violet transition-colors duration-500 group flex items-center gap-2"
            >
              View Our Work
              <span className="inline-block group-hover:translate-x-1 transition-transform duration-500">
                →
              </span>
            </a>
          </div>
        </div>

        {/* Trust bar */}
        <div
          ref={trustRef}
          className="mt-16 lg:mt-24 pt-8 border-t border-gray-200 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6"
        >
          <div className="flex items-center gap-8">
            {[
              { num: "12+", label: "Brands" },
              { num: "500+", label: "Deliverables" },
              { num: "5/5", label: "Rating" },
            ].map((stat) => (
              <div key={stat.label}>
                <p className="font-serif text-xl lg:text-2xl text-gray-800">
                  {stat.num}
                </p>
                <p className="font-sans text-[10px] text-gray-400 tracking-[0.15em] uppercase mt-0.5">
                  {stat.label}
                </p>
              </div>
            ))}
          </div>
          <p className="font-sans text-[10px] text-gray-300 tracking-[0.1em] uppercase">
            Trusted by e-commerce brands worldwide
          </p>
        </div>
      </div>
    </section>
  );
}
